### ISSUE TITLE
Fail to install

### ISSUE THREAD

**Issue by Vu168** [cid-harvard/py-ecomplexity#33]
I tried to install using pip install ecomplexity and encountered an error below. Appreciate if you could help. Thank you

error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [10 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\user\AppData\Local\Temp\pip-install-nsk2tobg\ecomplexity_855f1ab254084b4ca68c464addf11bdc\setup.py", line 13, in <module>
      long_description=readme(),
                       ^^^^^^^^
    File "C:\Users\user\AppData\Local\Temp\pip-install-nsk2tobg\ecomplexity_855f1ab254084b4ca68c464addf11bdc\setup.py", line 6, in readme
      return f.read()
             ^^^^^^^^
  UnicodeDecodeError: 'cp932' codec can't decode byte 0x93 in position 3468: illegal multibyte sequence
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by shreyasgm** [comment]
I'm not really able to reproduce this issue, so it's a bit hard to debug. My guess is that it's trying to install v0.3 of ecomplexity which I think had this issue. Updating your numpy and pandas, and then ecomplexity, should fix this issue. Closing this for now, but let me know if you have trouble with this with more recent versions of the package.
